import type { Metadata } from "next";
import "../globals.css";
import Footer from "@/components/Footer";
import Logo from "@/components/Logo";
import BrandName from "@/components/BrandName";
import Container from "@/components/Container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="mt-2 ml-2 flex items-center gap-4 w-max">
        <Logo />
        <BrandName />
      </div>

      <Container className="mt-20">
        {children}
      </Container>

      <Footer />
    </div>
  );
}
