import type { Metadata } from "next";
// import "@/app/globals.css";
import ProtectRoute from "@/components/ProtectRoute";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProtectedRouteLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ProtectRoute>
            {children}
        </ProtectRoute>
    );
}
