export const products = [
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a8b",
        name: 'Tractor',
        description: 'A powerful farming tractor.',
        price: 500000,
        pictures: ['https://example.com/tractor1.jpg', 'https://example.com/tractor2.jpg'],
        stock: 50,
        keyFeatures: ['High Horsepower', 'Efficient Fuel Consumption'],
        category: 'MACHINES',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2960',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a8c",
        name: 'Harvester',
        description: 'Automated crop harvester for efficient farming.',
        price: 800000,
        pictures: ['https://example.com/harvester1.jpg', 'https://example.com/harvester2.jpg'],
        stock: 30,
        keyFeatures: ['Crop Cutting Technology', 'Auto Navigation'],
        category: 'MACHINES',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2960',
    },
    {
        _id: '62b0c2d6a0f3c6cb0a8a8a8d',
        name: 'Organic Seeds Pack',
        description: 'A pack of high-quality organic seeds for various crops.',
        price: 200,
        pictures: ['https://example.com/seeds1.jpg', 'https://example.com/seeds2.jpg'],
        stock: 80,
        keyFeatures: ['Organic Certification', 'Wide Variety'],
        category: 'SEEDS',
        sellerType: "FARMER",
        sellerId: '5d378db134e20b4d7e6f295f',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a8e",
        name: 'Fertilizer Mix',
        description: 'Nutrient-rich fertilizer mix for healthy plant growth.',
        price: 50,
        pictures: ['https://example.com/fertilizer1.jpg', 'https://example.com/fertilizer2.jpg'],
        stock: 90,
        keyFeatures: ['Balanced Nutrients', 'Easy Application'],
        category: 'FERTILIZERS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2960',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a8f",
        name: 'Vegetable Seeds Assortment',
        description: 'Assorted vegetable seeds pack for home gardening.',
        price: 150,
        pictures: ['https://example.com/vegetableSeeds1.jpg', 'https://example.com/vegetableSeeds2.jpg'],
        stock: 60,
        keyFeatures: ['Variety Pack', 'Suitable for All Seasons'],
        category: 'SEEDS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2963',
    },
    {
        _id: '62b0c2d6a0f3c6cb0a8a8a90',
        name: 'Pesticide Spray',
        description: 'Effective pesticide spray for pest control.',
        price: 30,
        pictures: ['https://example.com/pesticide1.jpg', 'https://example.com/pesticide2.jpg'],
        stock: 70,
        keyFeatures: ['Safe for Plants', 'Long-lasting Protection'],
        category: 'PESTICIDES',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2963',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a91",
        name: 'Dairy Cow',
        description: 'Healthy dairy cow for milk production.',
        price: 80000,
        pictures: ['https://example.com/dairyCow1.jpg', 'https://example.com/dairyCow2.jpg'],
        stock: 20,
        keyFeatures: ['High Milk Yield', 'Well-fed and Vaccinated'],
        category: 'ANIMALS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a92",
        name: 'Cereal Mix',
        description: 'Assorted cereal mix for a nutritious breakfast.',
        price: 20,
        pictures: ['https://example.com/cereal1.jpg', 'https://example.com/cereal2.jpg'],
        stock: 100,
        keyFeatures: ['Whole Grains', 'Rich in Fiber'],
        category: 'CEREALS',
        sellerType: "FARMER",
        sellerId: '5d378db134e20b4d7e6f2965',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a93",
        name: 'Fruit Tree Sapling',
        description: 'Young fruit tree sapling for home orchards.',
        price: 100,
        pictures: ['https://example.com/sapling1.jpg', 'https://example.com/sapling2.jpg'],
        stock: 40,
        keyFeatures: ['Fast Growth', 'Fruit-bearing Variety'],
        category: 'FRUITS',
        sellerType: "FARMER",
        sellerId: '5d378db134e20b4d7e6f2962',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a94",
        name: 'Vegetable Cultivation Kit',
        description: 'Kit for cultivating a variety of vegetables at home.',
        price: 300,
        pictures: ['https://example.com/cultivationKit1.jpg', 'https://example.com/cultivationKit2.jpg'],
        stock: 25,
        keyFeatures: ['Seeds, Fertilizers, and Tools Included', 'Beginner-Friendly'],
        category: 'EQUIPMENTS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2963',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a95",
        sellerId: "5d378db134e20b4d7e6f2966",
        name: 'Milk Churn',
        description: 'Stainless steel milk churn for dairy farms.',
        price: 1500,
        pictures: ['https://example.com/milkChurn1.jpg', 'https://example.com/milkChurn2.jpg'],
        stock: 15,
        keyFeatures: ['Durable Construction', 'Easy to Clean'],
        category: 'EQUIPMENTS',
        sellerType: "DEALER"
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a96",
        name: 'Healthy Chicken',
        description: 'Healthy chicken for egg production.',
        price: 50,
        pictures: ['https://example.com/chicken1.jpg', 'https://example.com/chicken2.jpg'],
        stock: 45,
        keyFeatures: ['Egg-laying Breed', 'Free-range'],
        category: 'ANIMALS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a97",
        name: 'Farmers Hat',
        description: 'Comfortable hat for farmers during sunny days.',
        price: 10,
        pictures: ['https://example.com/hat1.jpg', 'https://example.com/hat2.jpg'],
        stock: 80,
        keyFeatures: ['Wide Brim', 'Breathable Fabric'],
        category: 'EQUIPMENTS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a98",
        name: 'Herbicide Spray',
        description: 'Effective herbicide spray for weed control.',
        price: 25,
        pictures: ['https://example.com/herbicide1.jpg', 'https://example.com/herbicide2.jpg'],
        stock: 65,
        keyFeatures: ['Selective Weed Control', 'Fast Action'],
        category: 'PESTICIDES',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "62b0c2d6a0f3c6cb0a8a8a99",
        name: 'Potato Seeds',
        description: 'High-quality potato seeds for planting.',
        price: 30,
        pictures: ['https://example.com/potatoSeeds1.jpg', 'https://example.com/potatoSeeds2.jpg'],
        stock: 75,
        keyFeatures: ['Certified Disease-free', 'Yields Healthy Potatoes'],
        category: 'SEEDS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4e1",
        name: 'Organic Manure',
        description: 'Organic manure for enriching soil fertility.',
        price: 15,
        pictures: ['https://example.com/manure1.jpg', 'https://example.com/manure2.jpg'],
        stock: 95,
        keyFeatures: ['Chemical-free', 'Slow-release Nutrients'],
        category: 'FERTILIZERS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4e2",
        name: 'Apple Tree Sapling',
        description: 'Young apple tree sapling for orchards.',
        price: 120,
        pictures: ['https://example.com/appleSapling1.jpg', 'https://example.com/appleSapling2.jpg'],
        stock: 35,
        keyFeatures: ['Fruit-bearing Variety', 'Suitable for Home Gardens'],
        category: 'FRUITS',
        sellerType: "FARMER",
        sellerId: '5d378db134e20b4d7e6f2965',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4e3",
        name: 'Corn Seeds',
        description: 'High-yielding corn seeds for cultivation.',
        price: 40,
        pictures: ['https://example.com/cornSeeds1.jpg', 'https://example.com/cornSeeds2.jpg'],
        stock: 85,
        keyFeatures: ['Large Kernels', 'Adaptable to Different Climates'],
        category: 'CEREALS',
        sellerType: "FARMER",
        sellerId: '5d378db134e20b4d7e6f2965',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4e4",
        name: 'Tomato Plant',
        description: 'Healthy tomato plant for home gardens.',
        price: 25,
        pictures: ['https://example.com/tomatoPlant1.jpg', 'https://example.com/tomatoPlant2.jpg'],
        stock: 55,
        keyFeatures: ['Plentiful Tomatoes', 'Compact Growth'],
        category: 'VEGETABLES',
        sellerType: "FARMER",
        sellerId: '5d378db134e20b4d7e6f2965',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4e5",
        name: 'Chicken Feed',
        description: 'Nutritious feed for poultry chickens.',
        price: 12,
        pictures: ['https://example.com/chickenFeed1.jpg', 'https://example.com/chickenFeed2.jpg'],
        stock: 60,
        keyFeatures: ['Balanced Nutrition', 'Promotes Egg Production'],
        category: 'ANIMALS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4e6",
        name: 'Rice Seeds',
        description: 'High-quality rice seeds for paddy fields.',
        price: 35,
        pictures: ['https://example.com/riceSeeds1.jpg', 'https://example.com/riceSeeds2.jpg'],
        stock: 70,
        keyFeatures: ['Short-duration Variety', 'High Yield'],
        category: 'CEREALS',
        sellerType: "FARMER",
        sellerId: '5d378db134e20b4d7e6f2965',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4e7",
        name: 'Goat',
        description: 'Healthy goat for milk and meat production.',
        price: 1000,
        pictures: ['https://example.com/goat1.jpg', 'https://example.com/goat2.jpg'],
        stock: 18,
        keyFeatures: ['Disease-resistant Breed', 'Adaptable to Various Climates'],
        category: 'ANIMALS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4e8",
        name: 'Spinach Seeds',
        description: 'Quality spinach seeds for home cultivation.',
        price: 18,
        pictures: ['https://example.com/spinachSeeds1.jpg', 'https://example.com/spinachSeeds2.jpg'],
        stock: 65,
        keyFeatures: ['Rich in Iron', 'Fast Germination'],
        category: 'VEGETABLES',
        sellerType: "FARMER",
        sellerId: '5d378db134e20b4d7e6f2965',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4e9",
        name: 'Hay Baler',
        description: 'Baler machine for baling hay on the farm.',
        price: 120000,
        pictures: ['https://example.com/hayBaler1.jpg', 'https://example.com/hayBaler2.jpg'],
        stock: 12,
        keyFeatures: ['Efficient Hay Baling', 'Easy Operation'],
        category: 'MACHINES',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4ea",
        name: 'Cow Feed',
        description: 'Nutritious feed for dairy cows.',
        price: 25,
        pictures: ['https://example.com/cowFeed1.jpg', 'https://example.com/cowFeed2.jpg'],
        stock: 75,
        keyFeatures: ['Promotes Milk Production', 'Balanced Diet'],
        category: 'ANIMALS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4eb",
        name: 'Carrot Seeds',
        description: 'High-quality carrot seeds for home gardens.',
        price: 15,
        pictures: ['https://example.com/carrotSeeds1.jpg', 'https://example.com/carrotSeeds2.jpg'],
        stock: 90,
        keyFeatures: ['Sweet and Crisp Carrots', 'Easy to Grow'],
        category: 'SEEDS',
        sellerType: "FARMER",
        sellerId: '5d378db134e20b4d7e6f2965',
    },
    {
        _id: "65bcd1f92e4f05b76af4e4ec",
        name: 'Sheep',
        description: 'Healthy sheep for wool and meat production.',
        price: 800,
        pictures: ['https://example.com/sheep1.jpg', 'https://example.com/sheep2.jpg'],
        stock: 25,
        keyFeatures: ['Soft Wool', 'Adaptable to Various Climates'],
        category: 'ANIMALS',
        sellerType: "DEALER",
        sellerId: '5d378db134e20b4d7e6f2966',
    },
    {
        _id: "65bcab6285eb3c1b9680478b",
        name: "Apple",
        description: "An apple is an edible fruit produced by an apple tree (Malus domestica. Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus.",
        price: 100,
        pictures: ["https://example.com/sheep1.jpg"],
        stock: 10,
        sellerType: "FARMER",
        category: "FRUITS",
        keyFeatures: ["Organic", "Fresh"],


        sellerId: "5d378db134e20b4d7e6f2965"
    },

    {
        _id: "65bcab6285eb3c1b9680478c",
        name: "Banana",
        description: "A banana is an elongated, edible fruit produced by several kinds of large herbaceous flowering plants in the genus Musa.",
        price: 200,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "FARMER",
        category: "FRUITS",
        keyFeatures: ["Organic", "Fresh"],


        sellerId: "5d378db134e20b4d7e6f2965"
    },
    {
        _id: "65bcab6285eb3c1b9680478d",
        name: "Tomatoes",
        description: "A tomato is a fruit of the plant Solanum lycopersicum, commonly known as a tomato plant. The species originated in South and Southeast Asia, where it is now grown as an annual crop.",
        price: 300,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "FARMER",
        category: "FRUITS",
        keyFeatures: ["Organic", "Fresh"],


        sellerId: "5d378db134e20b4d7e6f2965"
    },
    {
        _id: "65bcab6285eb3c1b9680478e",
        name: "Potatoes",
        description: "Potatoes are a root vegetable widely used in soups, stews, and casseroles.",
        price: 400,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "FARMER",
        category: "VEGETABLES",
        keyFeatures: ["Organic", "Fresh"],


        sellerId: "5d378db134e20b4d7e6f2965"
    },
    {
        _id: "65bcab6285eb3c1b9680478f",
        name: "Potato plants",
        description: "Will help you to grow new potatoes in your garden.",
        price: 200,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "DEALER",
        category: "SEEDS",
        keyFeatures: ["Organic", "Fresh"],


        sellerId: "5d378db134e20b4d7e6f2966"
    },
    {
        _id: "65bcab6285eb3c1b96804790",
        name: "Mnago seeds",
        description: "Will help you to grow new mangoes in your garden.",
        price: 200,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "DEALER",
        category: "SEEDS",
        keyFeatures: ["Organic", "Fresh"],


        sellerId: "5d378db134e20b4d7e6f2966"
    },
    {
        _id: "65bcab6285eb3c1b96804791",
        name: "Urea",
        description: "Will help you to increase crop yeild.",
        price: 200,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "DEALER",
        category: "FERTILIZERS",


        sellerId: "5d378db134e20b4d7e6f2966"
    },
    {
        _id: "65bcab6285eb3c1b96804792",
        name: "Calcium, Ammonium Nitrate",
        description: "Will help you to increase crop yeild.",
        price: 200,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "DEALER",
        category: "FERTILIZERS",


        sellerId: "5d378db134e20b4d7e6f2966"
    },
    {
        _id: "65bcab6285eb3c1b96804793",
        name: "Ammonium Sulphate",
        description: "Will help you to increase crop yeild.",
        price: 200,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "DEALER",
        category: "FERTILIZERS",


        sellerId: "5d378db134e20b4d7e6f2966"
    },
    {
        _id: "65bcab6285eb3c1b96804794",
        name: "Single Super Phosphate",
        description: "Will help you to increase crop yeild.",
        price: 200,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "DEALER",
        category: "FERTILIZERS",


        sellerId: "5d378db134e20b4d7e6f2966"
    },
    {
        _id: "65bcab6285eb3c1b96804795",
        name: "Potato",
        description: "Will help you to control various pests and disease carriers",
        price: 200,
        pictures: ["https://example.com/thmb/2S0qZ4kLh9b4D2yjyjNfH0aWvO0=/1500x0/filters:no_upscale(:max_bytes(150000:strip_icc(/apple-fruit-976372-01-5c8f9a9a46e0fb0001f0b3d1.jpg"],
        stock: 10,
        sellerType: "DEALER",
        category: "PESTICIDES",


        sellerId: "5d378db134e20b4d7e6f2966"
    },
]; // only for dev
